### PR TITLE
IZPACK-1528: Add progress listener to UninstallerListener#beforeDelete/InstallerListener#beforePacks

### PR DESCRIPTION
**Pull request by maichler**
Implementation of [IZPACK-1528](https://izpack.atlassian.net/browse/IZPACK-1528)

### CODE REVIEW

**Comment by rkrell** [comment]
Another complaint:
- I'd like to make this enhancement complete for all methods of InstallerListener and UninstallerListener, not just for `UninstallerListener#beforeDelete(java.util.List<java.io.File>)`. But not as a breaking change, but as enhancement. Wouldn't that be possible?

**Comment by maichler** [comment]
> Why we cannot keep the original method of the interface fully functional and just add the new one with the ProgressListener parameter?

I had considered this myself. However, if we kept the original method and added a new method with the additional parameter for the ProgressListener, how would we then ensure, that the interface works for both scenarios ? My initial thought was to implement a default behaviour in `AbstractUninstallerListener` like this:

```
    /**
     * Invoked before files are deleted.
     * <p>
     *     The default implementation calls {@link #beforeDelete(List)} for
     *     backwards compatibility.
     * </p>
     *
     * @param files all files which should be deleted
     * @param listener the progress listener
     * @throws IzPackException for any error
     */
    @Override
    public void beforeDelete(List<File> files, ProgressListener listener)
    {
        beforeDelete(files);
    }
```
While this works for all custom uninstall listeners extending `AbstractUninstallerListener`, it won't for those just implementing the interface. For that we'd need to call both methods in `UninstallerListeners` like so:

```
    /**
     * Invoked before files are deleted.
     *
     * @param files    all files which should be deleted
     * @param listener the progress listener
     * @throws IzPackException if a listener throws an exception
     */
    public void beforeDeletion(List<File> files, ProgressListener listener)
    {
        ProgressHandler handler = new ProgressHandler(listener, prompt);
        for (UninstallerListener l : listeners)
        {
            try
            {
                l.beforeDelete(files);
                l.beforeDelete(files, listener);
            }
            catch (IzPackException exception)
            {
                throw exception;
            }
            catch (Exception exception)
            {
                throw new IzPackException(exception);
            }
        }
    }
```
What do you think ?

**Comment by rkrell** [comment]
>             try
>             {
>                 l.beforeDelete(files);
>                 l.beforeDelete(files, listener);
>             }
> 

Exactly this could be avoided with the suggestion above:

> We could for instance add a default implementation to AbstractUninstallerListener
> ```java
>     @Override
>     public void beforeDelete(List<File> files, ProgressListener listener)
>     {
>         beforeDelete(files);
>     }
>```
> and you just override it if needed.
> In this case you could call
> ```java
>    l.beforeDelete(files, listener);
> ```
> in UninstallerListeners#beforeDeletion as desired.
>

**Comment by maichler** [comment]
> This would of course require to inherit from AbstractUninstallerListener instead of implementing UninstallerListener, but it would be a fast solution for migrating.

Ok, great ! I'll prepare an update to this pull request.

> I'd like to make this enhancement complete for all methods of InstallerListener and UninstallerListener, not just for UninstallerListener#beforeDelete(java.util.List<java.io.File>). But not as a breaking change, but as enhancement. Wouldn't that be possible?

I would have created another ticket and pull request for the InstallerListener. However, I was able to get a hold of a ProgressListener through injecting a reference to IUnpacker and retrieving the value of the private field `listener` ;) So I started with UninstallerListener, since there's absolutely no way of accessing any ProgressListener.

Anyway, do you think it is really necessary to add a ProgressListener to all methods ? As far as I know, the ProgressListener instance does not change during the lifetime of an uninstall listener. Therefor, a reference retrieved in beforePacks/beforeDelete could be kept in a field and accessed from within the other methods, if needed ?

**Comment by rkrell** [comment]
> Anyway, do you think it is really necessary to add a ProgressListener to all methods ?

Not to all methods, but those with lists which could take more time.
At least those with similar parameters like yours.

> As far as I know, the ProgressListener instance does not change during the lifetime of an uninstall listener. Therefor, a reference retrieved in beforePacks/beforeDelete could be kept in a field and accessed from within the other methods, if needed ?

I'd not make it more complicated than necessary.
My goal was just to get some basic kind of consistency to this API.
If you're unsure, leave it unchanged.
If it's too complex to do or takes too much time, I'll merge it and we can do this later.
This is just our spare time, right? ;-)

**Comment by maichler** [comment]
> Not to all methods, but those with lists which could take more time.
> At least those with similar parameters like yours.

Oh, I see. I know of `UninstallerListener#beforeDelete(List<File>, ProgressListener)` and `InstallerListener#beforePacks(List<Pack>, ProgressListener)`. Do you have any other listeners in mind which I'm not aware of ?

> I'd not make it more complicated than necessary.

Sorry if I was a bit unclear. I do not want to extend AbstractUninstallerListener any further. What I was trying to say is that any custom uninstall listener which wants access to a progress listener in any of the other methods could store a reference to ProgressListener in a local field.

> If it's too complex to do or takes too much time, I'll merge it and we can do this later.
> This is just our spare time, right? ;-)

I'm fine with it ;)  

So to be sure, should I update this pull request and add a ProgressListener to InstallerListener#beforePacks ? We should change the title of the issue, then too.

**Comment by rkrell** [comment]
> So to be sure, should I update this pull request and add a ProgressListener to InstallerListener#beforePacks ? We should change the title of the issue, then too.

I'd vote yes for it, this is very similar, to have this more complete.

**Comment by maichler** [comment]
Done!

**Comment by rkrell** [comment]
Thank you.

**Pull request merged**
