### PR TITLE
Fixed problem with XDG shortcuts https://groups.google.com/forum/#!to…

### PR DESCRIPTION
**Pull request by ThibLind**
Dear IzPack developers,

Some time ago, I reported two problems (one on Linux and one on Windows) with shortcuts, please see **https://groups.google.com/forum/#!topic/izpack-user/UrLck2vG-6U** . This is the fix for the problem under Linux. If you accept this patch, then I will submit the other patch for the Windows problem.

Sincerely,

Thibault LINDECKER

PS: Thank you for this great free software!

### CODE REVIEW

**Comment by reinhapa** [comment]
@ThibLind could you update you're feature branch with the latest changes?

**Comment by ThibLind** [comment]
Hello,

Thank you for your response. It's done.

Sincerely,

Thibault LINDECKER

**Review by akuhtz — APPROVED** [review]
The PR is not rebased but the only change is the check for not empty startMenuShortcuts and this LGTM.

**Comment by reinhapa** [comment]
@ThibLind can you rebase your change in order to be merged?

**Comment by ThibLind** [comment]
All is good for you now ?

**Comment by akuhtz** [comment]
:+1:

**Comment by reinhapa** [comment]
@akuhtz have you already opened an issue?

**Comment by akuhtz** [comment]
@reinhapa See https://izpack.atlassian.net/browse/IZPACK-1690

**Comment by akuhtz** [comment]
@ThibLind Would you update the patch with the fix for Windows? That would be less work for us :wink:

**Comment by reinhapa** [comment]
@akuhtz is there any work left to do before merge?

**Comment by akuhtz** [comment]
@reinhapa Yes, there is a fix for Windows OS in the referenced google groups thread. I have not seen this earlier unfortunately. But maybe merge this PR now and have another for the Windows issue.

**Pull request merged**
