### PR TITLE
Expired checker

### PR DESCRIPTION
**Pull request by optotronic**
This checker lets installers automatically expire on a date specified by variable "InstallerExpiresDate" in the installer XML file.  The date must be in the format "yyyy-MM-dd".  If "InstallerExpiresDate" is not defined, the installer does not expire.

### CODE REVIEW

**Comment by rkrell** [comment]
Thank you for this contribution.
Would you please make a JIRA issue from that for us to get a clean changelog, please.
Please add also a usage example to that issue and primarily document this in Confluence.
If you do so in time, this would be probably the last new feature to 5.0 RC5 and might me to 5.0.0 before finally releasing it.

**Comment by optotronic** [comment]
Thanks, René.  Who do I talk to to get JIRA and Confluence accounts?

**Comment by rkrell** [comment]
You should be able to register on Codehaus Xircles. With the account there
you can go further.

2015-02-05 16:47 GMT+01:00 optotronic <notifications@github.com>:

**Comment by rkrell** [comment]
If you grab a Xircles account, login and look here:
- http://jira.codehaus.org/browse/IZPACK
Raise an issue with a new feature. We can generate some kind of changelog from that for announcements.
- http://docs.codehaus.org/display/IZPACK/Dynamic+Installer+Requirements
This page is maybenot complete, you might improve it from what you see in the code.
At least mention the usage of the Expriry Checker here and how to use it.

Thank you

**Comment by optotronic** [comment]
Thanks, René. I'm still waiting for the Xircles verification email.  It's been > 45 minutes.

**Comment by optotronic** [comment]
I tried creating three different accounts in Xircles with three different emails, usernames, and passwords, but have not received any verification emails yet.  I sent an email to support at codehaus.org but received no response.  It looks like I can't raise an issue about not being able to create an account without an account.  When I get an account I'll create the JIRA request and update the docs.

BTW, your Contributing+Code+Changes doc looks very useful.  Wish I'd seen it before I started!

**Comment by rkrell** [comment]
Oh really? Did you try to raise an issue to http://jira.codehaus.org/secure/BrowseProject.jspa?id=10104 ? Didn't it end in a spam folder? ;-)

The Contributing+Code+Changes has been completed one by one from the view of a developer knowing Java but not being so familar with Git and Github. There are just a very few basics of handling code changes and a pull request, just to have a checklist of the essential steps.

**Comment by optotronic** [comment]
The codehaus.org mail server is on the spamrats.com blacklist, and the emails were bounced before they got to my mailbox.  (The messages did not appear in any spam filters or folders accessible to me.)  I successfully used an email account on a different domain that did not use this blacklist to create my accounts.

I created a [JIRA issue IZPACK-1219](http://jira.codehaus.org/browse/IZPACK-1219).  I also added to the [Dynamic Installer Requirements](http://docs.codehaus.org/display/IZPACK/Dynamic+Installer+Requirements) page you referenced.

**Comment by rkrell** [comment]
Thanks for contributing

**Pull request merged**
