### PR TITLE
[IZPACK-1192] If no PacksPanel specified install dies with Cannot find named resource: 'packsLang.xml AND 'packsLang.xml_eng'

### PR DESCRIPTION
**Pull request by hiteshbosamiya**

### CODE REVIEW

**Comment by akuhtz** [comment]
@hiteshbosamiya Do you have a test project that shows the issue?

**Comment by hiteshbosamiya** [comment]
Attached test-1192.zip to the ticket.

**Comment by akuhtz** [comment]
@hiteshbosamiya Is it possible for you to add the test-1192 as an integration test under ```izpack\izpack-maven-plugin\src\it``` ?

**Comment by hiteshbosamiya** [comment]
added test-1192 as an integration test `izpack-1192` under `izpack\izpack-maven-plugin\src\it`

**Comment by akuhtz** [comment]
@reinhapa I accidentially push a ```pr747``` branch to the izpack repo but I cannot delete it. Can you delete this branch?

**Comment by reinhapa** [comment]
> @reinhapa I accidentially pushed a `pr747` branch to the izpack repo but I cannot delete it. Can you delete this branch?
@akuhtz done

**Review by akuhtz — APPROVED** [review]

**Pull request merged**
