### PR TITLE
Travis udpate

### PR DESCRIPTION
**Pull request by reinhapa**
@rkrell I stumbled over some travis issues when running with my #658 pull request. This will fix the build and enhances the _PrivilegedRunnerTest_ to include also the JVM arguments, that may be differ on the travis build environment

### CODE REVIEW

**Comment by reinhapa** [comment]
@rkrell locally it's not a problem, it seems the the travis environment upgraded the version... I may have to download an earlier version then.

**Comment by reinhapa** [comment]
@rkrell I had to add a script forcing the installation of maven 3.2.5 in order to get the build running

**Comment by rkrell** [comment]
> @rkrell I had to add a script forcing the installation of maven 3.2.5 in order to get the build running
@reinhapa Thanks a lot for.

**Comment by rkrell** [comment]
> @rkrell I had to add a script forcing the installation of maven 3.2.5 in order to get the build running

We should probably do a user poll who is still at JDK 6, but I know about at least one company :-)

**Comment by rkrell** [comment]
Great job, thank you.

**Comment by reinhapa** [comment]
@rkrell you're welcome. going make izpack jdk 9 ready now :-)

**Pull request merged**
