### PR TITLE
IZPACK-1400  Maven Build: installer does not recognize external overwritten property

### PR DESCRIPTION
**Pull request by Helpstone**
see https://izpack.atlassian.net/browse/IZPACK-1400

### CODE REVIEW

**Comment by rkrell** [comment]
Hi @Helpstone, like already commented in https://izpack.atlassian.net/browse/IZPACK-1402 I'd rather like to define a clean concept instead of making partial implementations.

At the moment we are a bit lost in mixing properties and variables, further more we need some configuration facility here instead of breaking anything for others. I know installers in our environment which wouldn't work any longer without bigger efforts after this change.

**Comment by Helpstone** [comment]
Yes, the properties and variables are mixed together nowadays. But this is not a result of this pull request. 

Adding additional (user) properties is a potential dangerous change and therefore I've created **IZPACK-1402**. In future there should be a way to determine which properties are provided to the installer runtime. But now and in future the properties, which are provided, should be provided with ther correct value!

**But IZPACK-1400 is IMHO not dangerous to existing installers!** Only the properties found in pom.xml will be searched in user properties. All other user properties are ignored. So it does NOT add additional properties.It just provides the properties, which were already available up to now, with the correct value (as the user will expect).

Did you honor this fact? Do you really know installers, which would be damaged by this pull request?

**Comment by rkrell** [comment]
Ok and sorry for the late answer.

Maybe my fault, the properties from POM should get in at the moment, that's what I wanted.
I'll merge this and test our installer with the snapshot state. We'll see whether there are broken use cases.

Thank you, @Helpstone.

**Comment by Helpstone** [comment]
No problem, the answer has not been late. It is important to check, whether merges could break exisiting installers.
I am sure, IZPACK-1400 will not do so, but importing all user set properties could do so. Therefore we should work carefully on IZPACK-1402 at some day.

**Pull request merged**
