### PR TITLE
added checkstyle-maven-plugin in order to reduce future merge workload

### PR DESCRIPTION
**Pull request by krichter722**
Motivation: doing this aweful work once seems a lot of effort and it is, but it will pay off over time by making almost every merge a tiny bit smaller and better to read. Integration into the build tool with the `maven-checkstyle-plugin` is very efficient in my experience. No functional changes has been made to the code.

Notes:

  * The formatting of comments was difficult to avoid and has to be removed manually. If you insist, I can remove it.
  * Some changes like renaming `final static logger` to `LOGGER` is controversial in terms of practices, but reduces controversy in terms of merge workload based on static analysis
  * some meaningful changes like renaming of methods and method parameter is deactived until http://stackoverflow.com/questions/42469047/how-to-exclude-native-methods-from-checkstyles-methodname-module is clarified
  * It'd be nice to have a common header which can be checked.
  * Some tests fail which is a blocker for merging this. I'm trying to figure this out, don't hesitate to step in.
  * Some changes performed by the formatter I had to use to deal with the amount of code will not be enforced by `checkstyle`, but they can be added since `checkstyle` can enforce almost everything.

### CODE REVIEW

**Comment by rkrell** [comment]
BTW: I'd also like to consolidate all the license headers in the source code. The license text should be the same for every source code file, with the possibility of changing it globally with every release, for example for adding the year.
Do you know a proper plugin or approach to automatize this?

**Comment by krichter722** [comment]
> BTW: I'd also like to consolidate all the license headers in the source code. The license text should be the same for every source code file, with the possibility of changing it globally with every release, for example for changing the year.
Do you know a proper plugin or approach to automatize this?

[We used `org.codehaus.mojo:license-maven-plugin:1.8` once](https://github.com/mjsax/aeolus/blob/master/pom.xml), but it had some tradeoff. I think it recognized the header with a bunch of ugly potential unwanted marker symbols.

I add checkstyle at a very early stage to my projects for years and go with static analysis and manual changes only - which doesn't help in this case, of course :), because changing > 1000 files is not an option.

**Comment by rkrell** [comment]
Would you mind to delay this until I send a pull request which I'm working on a couple of weeks and which also moves several files to different modules? I assume the checkstyle plugin does an automatic check on demand, so it should be easier for you to rerun it than to get a lot of merge conflicts.

**Comment by krichter722** [comment]
> Would you mind to delay this until I send a pull request which I'm working on a couple of weeks and which also moves several files to different modules? I assume the checkstyle plugin does an automatic check on demand, so it should be easier for you to rerun it than to get a lot of merge conflicts.

No, there's no way we'll sort out the Java 6 issue soon and if there're two major unrelated changes one of us has to rebase anyway, so that might as well be me.

**Comment by krichter722** [comment]
The test failure `XmlMergeTest.testMergeFilesWithXPathTagMatcherReplace2Files:172 Result document does not match expected result` happens due to changes in the indentation in XML documents. Do you prefer to change tests to match the level of indentation or to exclude XML files from the change (they're excluded from the checks in `checkstyle`, but are part of the PR because of the formatter which has been used and it makes sense to include them in the future). I prefer the latter.

**Comment by rkrell** [comment]
Do you have plans to continue with this?
I think before doing this there should be an agreement about a code freeze for a couple of days to not produce merge conflicts. Unfortunately we cannot freeze the code for a longer time because there is always some maintenance work to do in the code and there is a couple of contributors doing more awful work.

**Comment by rkrell** [comment]
I'll close this one for no further response.
Please send a new PRagainst the latest state if you are still interested to support this.
Thanks.

**Pull request closed without merging**
