### PR TITLE
Clear executables list after unpack the current pack.

### PR DESCRIPTION
**Pull request by akuhtz**
Clear executables list after unpack the current pack. 
See discussion here: https://groups.google.com/forum/#!topic/izpack-user/8Ahrm2MOYE0

### CODE REVIEW

**Comment by rkrell** [comment]
Thank you.
If I look at the [UnpackerBase](https://github.com/izpack/izpack/blob/master/izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java) code I stumbled over some more trouble of this kind:
Beyond executables, isn't this also a problem for parsables and updatechecks?

See [UnpackerBase.java lines 493-495](https://github.com/izpack/izpack/blob/master/izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java#L493-L495), and the following two lines, it is the same for all of them, they add entries to lists for each packInputStream without clearing the list.

Maybe we should just remove the List instances from the methods interface and make it a private field of [UnpackerBase](https://github.com/izpack/izpack/blob/master/izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java). What do you think?

**Comment by rkrell** [comment]
Furthermore [UnpackerBase.java lines 709](https://github.com/izpack/izpack/blob/master/izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java#L709):
This method doesn't use the parameter ``List<UpdateCheck> updateChecks`` at all.

**Comment by akuhtz** [comment]
I moved the list instances to the unpack method were they are used and added a new test method to MultiVolumeUnpackerTest.
I'm not sure if the test is correct or if the createPack() method should have a better implementation for the test. 

Also I'm not sure if adding the Lists as instance variables is really a better solution as they are only used locally at the moment.

**Comment by rkrell** [comment]
I don't see a bad practise in adding private fields initialized and used locally.
It is rather "unusual" to initialize empty instance, pass them as method parameter and expect the method to fill and implicitly return them initialized. This has the taste of C malloc() :-)

**Comment by rkrell** [comment]
Well done so far, I like unit tests :-)

**Comment by rkrell** [comment]
Added an issue for this for the changelog: https://izpack.atlassian.net/browse/IZPACK-1321

**Comment by rkrell** [comment]
Thanks for contributing.

**Pull request merged**
