### PR TITLE
[IZPACK-1707] Add long arguments support to Uninstaller (-console/-force)

### PR DESCRIPTION
**Pull request by Toilal**
This make uninstaller arguments more consistent with installer ones.

### CODE REVIEW

**Review by akuhtz — CHANGES_REQUESTED** [review]
@Toilal  There is another `-f` on line 159. Would you mind update the PR to have this replaced, too?

**Comment by Toilal** [comment]
Just updated it, there's also a "-x" but I don't know what to use for a long label on this flag.

**Comment by akuhtz** [comment]
The `-x` option is to select the _delete all_ checkbox option in the uninstaller dialog as far as I understand. But I have no long good wording for this either :-)

**Comment by rez-** [comment]
why not "--force"? 2 dashes seems more like the standard to me. Also why not --delete-all for the -x?

**Comment by Toilal** [comment]
the `-x` option is use to hide the checkbox labeled "Force the deletion of", so it should be  something like `-hide-force-option`.

I'll add a commit with double dashes and this change.

**Comment by Toilal** [comment]
Well ... Maybe addining 2 dashes support for every options (Uninstaller and Installer) should belong to another pull request.

**Review by akuhtz — APPROVED** [review]

**Comment by reinhapa** [comment]
@akuhtz is there any IZPACK issue for this?

**Comment by akuhtz** [comment]
@reinhapa I don't think so. I can create one.

**Pull request merged**
