### PR TITLE
Allow -auto argument without -defaults-file

### PR DESCRIPTION
**Pull request by Toilal**
This change allow to use `-auto` argument without providing any `-defaults-file`. 

I'm a new user of IzPack, and the whole purpose of an installer is to build a single file for the package. But I could not run the `-auto` installation without providing an aditionnal `-defaults-file` file. I could not understand this behavior and was really frustrated to discover this limitation after spending some time to learn the framework and build the whole installer, so here's a pull request that I have tested against my installer project.

IzPack is a nice piece of software tough, I wrote again a Swing JPanel 10 years after good old times, thanks for maintaining it.

### CODE REVIEW

**Comment by mezmerize** [comment]
This commit most likely breaks automatic installation methods other than defaults with the removal of command line args checks. I like the idea of installing completely without defaults though.

**Comment by Toilal** [comment]
True, maybe the `NoOverrides` class was not a so good idea, i'll try another implementation ...

**Comment by Toilal** [comment]
@mezmerize Please take a look at this new version. There's still an `AutomatedOverrides` class, but it's constructed deeper in the installer workflow, just before invoking `processOptions` method, so it doesn't change the behavior of automated runs with a provided `auto-install.xml` file.

I have tested manually on my installer and it seems to work as expected (manual, `-console`, `-auto` without defaults, with or without an input `auto-installer.xml` file)

**Comment by Toilal** [comment]
I don't know why github actions tests are failing, tests are OK at home on both Windows and Linux.

**Comment by akuhtz** [comment]
@mezmerize Can you take a look at this? I never used automatic installations so far.

**Review by mezmerize — APPROVED** [review]
👍 
I am sorry for the late response, I tried the behavior with and without defaults, looks ok to me.

**Comment by akuhtz** [comment]
@mezmerize Thank you :-)

**Pull request merged**
