### PR TITLE
IZPACK-1103: fix "Resource leak: 'jis' is not closed at this location"

### PR DESCRIPTION
**Pull request by Helpstone**
minor correction, may be delayed after 5.0.7

### CODE REVIEW

**Comment by rkrell** [comment]
The bug is actually there, but I found this method isn't used at all in the code.
Shouldn't we rather remove old code?

**Comment by Helpstone** [comment]
Well, unused code should be removed. There's a lot of code and shortening will make it more clean.

But can we be sure, that no one is using this class in a custom extension of IzPack? I have no idea, why somebody should use this method in a custom panel for example. But it could be possible.

So I would suggest to mark the method deprecated first and remove later. There are a lot of deprecated methods - is there a plan when to remove?

**Comment by rkrell** [comment]
We cannot be sure, but this is obviously crap.
We cannot keep utility methods forever and everyone can write them by its own easily.
I know, normally they should be marked deprecated, but this stuff is useless. No need for this from my point of view. The IzPack overhead should be as small as possible.
I've already removed a lot of such stuff the ast few months, no complaints so far. Sometimes some people hat to adapt something to a small API change, but never dramatically.

**Comment by Helpstone** [comment]
you are the master :-)

I do not think, that anybody is using this method, so you may remove it.

But because of the 5.0.7-Snapshot testing already one by several people, I would remove it on 5.0.8

**Comment by rkrell** [comment]
Good idea. Let's clean up a bit more in 5.0.8.
You might refresh this pull request and remove it for you if you want.
In case you'll find other useless code let's discuss whether it makes sense to leave it, mark it deprecated or throw it away immediately. I'm sure we will find some more. Our tools will help us :-)

**Comment by rkrell** [comment]
Thanks for this code cleanup.

**Pull request merged**
