### PR TITLE
IZPACK-1491: Translation package bra for console installation

### PR DESCRIPTION
**Pull request by guilherfp**
This PR provides the change for [IZPACK-1491](https://izpack.atlassian.net/browse/IZPACK-1491).

### CODE REVIEW

**Comment by rkrell** [comment]
From what I can see you didn't change any translation, but you adapted the file encoding to what is defined in the XML header - iso_8859_1, right?

Formally this is correct, but wouldn't it be better to change the header encoding to UTF-8 and save the file as UTF-8, to not have so much encoding types. The file has been probably saved in UTF-8 and there has just been left the wrong encoding definition in its header.

UTF-8 is the default encoding in Java and for most parsers nowadays if they do not consider the encoding definition in the header. And it should cover your native language very well.

What do you think?

**Comment by guilherfp** [comment]
I corrected the previous committee

**Comment by rkrell** [comment]
This looks fine. Thank you.

I'd just like to ask you one last request: Do you have a JIRA account at https://izpack.atlassian.net?
Would you mind to create short issue there and link it to this request for getting a complete changelog for the end users, please?

**Comment by rkrell** [comment]
Thanks for this contribution.

**Pull request merged**
