### PR TITLE
Adding PDF Licence Panel

### PR DESCRIPTION
**Pull request by diegovivo**
I implemented a simple licence panel using icepdf.

please validate if it can be incorporated to the codebase.

Best Regards,
Diego

### CODE REVIEW

**Comment by diegovivo** [comment]
additional work

**Comment by rkrell** [comment]
Hi Diego,

thanks for this effort.

I'm pretty impressed, please just verify the following: For users NOT using this it should not be necessary to compile all the dependent jars into the installer. Instead, if on uses this new panel, the necessary additional jars should be added using the <jar> tag. I'd deny any additional classes or resources from the 3rd-party libraries in any default installer to not blow them up. The icepdf and all additional jars can be used for compiling, but should not be necessarily required for installers not using this feature. I'm currently thinking about how to introduce more modularity into IzPack, something like OSGI. Can you ensure this so far? Please verify resulting installers without the PDFLicencePanel not to have classes of those libraries inside.
Furthermore, before merging, can you please prepare the documentation for this new panel in Confluence (or in worst case attached here) and how to use this, please?

I would appreciate remove the formatting changes in the POMs to better see the diff here.

Thank you so far for contributing,
René

**Comment by diegovivo** [comment]
To achieve such behavior I believe we can set the pdf licence panel dependencies as provided (<scope>provided</scope>) and include them either in the plugin dependencies or in the project dependencies.

**Comment by rkrell** [comment]
Primarily please test, whether an installer jar generated from that code NOT using a PDFLicencePanel does not contain any classes from the dependent libraries, hence whether they are not merged in during compiling (recursively as resources in the root path in the jar). They shouldn't in theory, but better give it a try. If you can confirm this I will test this also. Thanks.

**Comment by rkrell** [comment]
Any news? I'd really like to see this in 5.0.7, please just check my previous comment, to be prepared for this feature.

**Comment by diegovivo** [comment]
René,

Sorry for the delayed answer.

I'm currently on vacations.

next friday I'll be back on the office and I'll keep working on the pdf
displayer.

2016-01-13 6:19 GMT-02:00 René Krell <notifications@github.com>:

> Any news? I'd really like to see this in 5.0.7, please just check my
> previous comment, to be prepared for this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/izpack/izpack/pull/406#issuecomment-171213180>.
>



-- 
Diego Vieira Vivo

**Comment by diegovivo** [comment]
Rene,

to use the panels you just need to change the following 2 lines in red and
add the 2 lines in blue on the install.xml.
I tried to keep the same standard as you. there is no other change.


<resources>
**
*<res id="PDFLicencePanel.licence" src="resources/legalNotice.pdf" />*
<res id="userInputSpec.xml" src="resources/userInputSpec.xml" />
<res id="userInputLang.xml_eng" src="resources/userInputLang.xml_eng" />
<res id="XInfoPanel.info" src="resources/postInstall.txt" parse="yes" />
</resources>


<panels>
<panel classname="HelloPanel" id="hello" />
**
*<panel classname="PDFLicencePanel" id="licence" />*
<panel classname="TargetPanel" id="target" />
<panel classname="PacksPanel" id="packs" />
<panel classname="UserInputPanel" id="UserInputPanel.0" />
<panel classname="InstallPanel" id="install" />
<panel classname="XInfoPanel" id="info" />
<panel classname="FinishPanel" id="finish" />
</panels>

Because I Included the classes on the izpack-panel project and registered
it on DefaultClassNameMapper (izpack compiler) the use is simple.

As you requested I included I made the transitive dependencies have the
*"provided"* scope therefore they won't be included on the packaged unless
they are explicitly added.

The PDFLicencePanel could be in its own jar file decreasing the coupling
level.  The place where I was struggling when trying to do that was when
tying everything together, since I couldn't find a hook on the
DefaultClassNameMapper to add the PDFLicencePanel via configuration without
changing the source code.

if you could help me I'd be glad. :)




2015-12-21 9:00 GMT-02:00 René Krell <notifications@github.com>:

> Hi Diego,
>
> thanks for this effort.
>
> I'm pretty impressed, please just verify the following: For users NOT
> using this it should not be necessary to compile all the dependent jars
> into the installer. Instead, if on uses this new panel, the necessary
> additional jars should be added using the tag. I'd deny any additional
> classes or resources from the 3rd-party libraries in any default installer
> to not blow them up. The icepdf and all additional jars can be used for
> compiling, but should not be necessarily required for installers not using
> this feature. I'm currently thinking about how to introduce more modularity
> into IzPack, something like OSGI. Can you ensure this so far? Please verify
> resulting installers without the PDFLicencePanel not to have classes of
> those libraries inside.
> Furthermore, before merging, can you please prepare the documentation for
> this new panel in Confluence (or in worst case attached here) and how to
> use this, please?
>
> I would appreciate remove the formatting changes in the POMs to better see
> the diff here.
>
> Thank you so far for contributing,
> René
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/izpack/izpack/pull/406#issuecomment-166270974>.
>



-- 
Diego Vieira Vivo

**Comment by rkrell** [comment]
For the current implementation it isn't really practical to separate features to jars.
I'd really appreciate such a feature, but this will most probably require a bigger refactoring of the whole core. I'd like some OSGI style with a light-weight OSGI framework.
Can you please document this as [Built-in panel type](https://izpack.atlassian.net/wiki/x/PIAH) in Confluence, please?

**Comment by rkrell** [comment]
Sorry, there appeared some conflicts due to the latest merged changes to the master.
Are you able to resolve this, please? Will be probably easy.

One more hint: Regarding commit https://github.com/diegovivo/izpack-1/commit/39d29bed26f7a1ca28e0d79170bc489c0dc967cf - this should be solved by excludes/includes in the master POM - just include it to the profile ```with-gui-tests``` and exclude it above, just find ```LanguageDialogTest.java``` to see how this is done.

**Comment by diegovivo** [comment]
Could you provide more details?
I don't have access to see them

2016-01-19 21:13 GMT-02:00 René Krell <notifications@github.com>:

> Sorry, there appeared some conflicts due to the latest merged changes to
> the master.
> Are you able to resolve this, please? Will be probably easy.
>
> One more hint: Regarding commit diegovivo@39d29be
> <https://github.com/diegovivo/izpack-1/commit/39d29bed26f7a1ca28e0d79170bc489c0dc967cf>
> - this should be solved by excludes/includes in the master POM - just
> include it to the profile with-gui-tests and exclude it above, just find
> LanguageDialogTest.java to see how this is done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/izpack/izpack/pull/406#issuecomment-173018602>.
>



-- 
Diego Vieira Vivo

**Comment by rkrell** [comment]
I added issue [IZPACK-1312](https://izpack.atlassian.net/browse/IZPACK-1312) to complete the release log.
Please let me know if you are registered in JIRA, in this case I can assign you as reporter.

**Comment by rkrell** [comment]
> Could you provide more details?
> I don't have access to see them

What I meant is in your local source code branch, just open the parent pom.xml, find ```LanguageDialogTest.java``` and include/exclude your panel test in the same way. The Maven profile ```with-gui-tests``` must be explicitly executed on a local machine if one needs to launch GUI unit tests, it won't be automatically run if you exclude it from the default surefire run. This way you can revert this commit and annotate your test as ```@Test```.

**Comment by rkrell** [comment]
Please merge in the latest izpack/master to your local code and resolve any conflict. AFAIK there haven't been any direct conflicts with your changes, it seems to be rather a history or formatting problem, probably in some POM.

**Comment by diegovivo** [comment]
René,
Manage to merge.
Could you please verify?

**Comment by diegovivo** [comment]
after you approve I'll close the the pull request

**Comment by rkrell** [comment]
Thank you for contributing.

I merged this and this request is closed automatically.
I'd appreciate if you could document this a bit. I created an empty Confluence page https://izpack.atlassian.net/wiki/display/IZPACK/PDFLicencePanel in the User Documentation, if you would be so kind and fill some contents, how to use it, an example how to add it to install.xml. A screenshot would be also welcome. Whatever you're able to do.. Thanks

**Comment by rkrell** [comment]
I resolved also the according JIRA issue for the changelog: https://izpack.atlassian.net/browse/IZPACK-1312

**Comment by rkrell** [comment]
For the PDFLicenceConsolePanel, there apply also the new configuration options of the console installation mode according to [IZPACK-1318](https://izpack.atlassian.net/browse/IZPACK-1318).

**Comment by rkrell** [comment]
I sent a question to the ICEpdf forum whether they would be so kind to deploy their OSS releses to an official repository:
http://www.icesoft.org/JForum/posts/list/23061.page#top
If there will be no answer I'll try to send them an issue.

I don't like the `<repository>` in the parent POM, it causes depending Maven projects using the IzPack Maven plugin downloading artifacts also from their repository:
```
08:25:28 [INFO] Scanning for projects...
08:25:29 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-maven-plugin/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:30 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-maven-plugin/5.0.7-SNAPSHOT/maven-metadata.xml (1000 B at 0.6 KB/sec)
08:25:30 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:31 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack/5.0.7-SNAPSHOT/maven-metadata.xml (814 B at 1.1 KB/sec)
08:25:31 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:31 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:32 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml (2 KB at 2.2 KB/sec)
08:25:32 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:32 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:32 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml (994 B at 5.2 KB/sec)
08:25:32 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:32 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:33 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml (828 B at 1.4 KB/sec)
08:25:33 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:33 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 1.0 KB/sec)
08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml (991 B at 4.8 KB/sec)
08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 3.1 KB/sec)
08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml (992 B at 3.8 KB/sec)
08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml (997 B at 4.9 KB/sec)
08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml (992 B at 4.2 KB/sec)
08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml (991 B at 4.7 KB/sec)
08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 4.1 KB/sec)
08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml
08:25:36 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml (999 B at 4.4 KB/sec)
```

**Comment by diegovivo** [comment]
Rene,

Can I ask you a favor ?

On the Bottom of the PDFLicencePanel Class I initialize the icepdf.
At time I'd like to use parameters from the install XML but I didn't know
how to do it and hadn't the time to research.

Could you choose the choose the parameters you'd like to have configurable
and let me know or if you prefer could you implemement?

Probably I'll have some availability on Wednesday.


Thanks in advance.

Diego


On Wednesday, 3 February 2016, René Krell <notifications@github.com> wrote:

> I sent a question to the ICEpdf forum whether they would be so kind to
> deploy their OSS releses to an official repository:
> http://www.icesoft.org/JForum/posts/list/23061.page#top
> If there will be no answer I'll try to send them an issue.
>
> I don't like the <repository> in the parent POM, it causes depending
> Maven projects using the IzPack Maven plugin downloading artifacts also
> from their repository:
>
> 08:25:28 [INFO] Scanning for projects...
> 08:25:29 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-maven-plugin/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:30 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-maven-plugin/5.0.7-SNAPSHOT/maven-metadata.xml (1000 B at 0.6 KB/sec)
> 08:25:30 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:31 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack/5.0.7-SNAPSHOT/maven-metadata.xml (814 B at 1.1 KB/sec)
> 08:25:31 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:31 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:32 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-compiler/5.0.7-SNAPSHOT/maven-metadata.xml (2 KB at 2.2 KB/sec)
> 08:25:32 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:32 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:32 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native/5.0.7-SNAPSHOT/maven-metadata.xml (994 B at 5.2 KB/sec)
> 08:25:32 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:32 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:33 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-native-parent/5.0.7-SNAPSHOT/maven-metadata.xml (828 B at 1.4 KB/sec)
> 08:25:33 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:33 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-panel/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 1.0 KB/sec)
> 08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-api/5.0.7-SNAPSHOT/maven-metadata.xml (991 B at 4.8 KB/sec)
> 08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-tools/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 3.1 KB/sec)
> 08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-util/5.0.7-SNAPSHOT/maven-metadata.xml (992 B at 3.8 KB/sec)
> 08:25:34 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:34 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-installer/5.0.7-SNAPSHOT/maven-metadata.xml (997 B at 4.9 KB/sec)
> 08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-core/5.0.7-SNAPSHOT/maven-metadata.xml (992 B at 4.2 KB/sec)
> 08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-gui/5.0.7-SNAPSHOT/maven-metadata.xml (991 B at 4.7 KB/sec)
> 08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-event/5.0.7-SNAPSHOT/maven-metadata.xml (993 B at 4.1 KB/sec)
> 08:25:35 [INFO] Downloading: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:35 [INFO] Downloading: http://anonsvn.icesoft.org/repo/maven2/releases/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml
> 08:25:36 [INFO] Downloaded: http://build.mycompany.com/nexus/content/groups/public-snapshots/org/codehaus/izpack/izpack-uninstaller/5.0.7-SNAPSHOT/maven-metadata.xml (999 B at 4.4 KB/sec)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/izpack/izpack/pull/406#issuecomment-179107416>.
>


-- 
Diego Vieira Vivo

**Comment by rkrell** [comment]
You can add configuration options to a panel this way:
```xml
<panel id ="..." ...>
  <configuration>
   <option_name>option_value</option_name>
  </configuration>
</panel>
```

To access this, get an instance of Panel:
- `LicencePanel`: `getMetaData()`
- `LicenceConsolePanel`: `getPanel()`

A `Panel` inherits from `DefaultConfigurationHandler`, which has the appropriate methods to read these parameters. I have implemented this recently, so be up to date with _master_.

Please avoid committing right now, because I have prepared some refactoring of all license panels, to extract an abstraction layer for them an unify their behavior regarding the license document resources. See [IZPACK-1329](https://izpack.atlassian.net/browse/IZPACK-1329).

**Comment by rkrell** [comment]
@diegovivo I thing you can go on now, the mentioned changes are merged, the master is up to date.

You would be welcome with this change. I think you should do it, you probably know the ICEpdf framework better than me. If you would be so kind please update the documentation after this.

Thank you for your effort.

**Pull request merged**
