### PR TITLE
Fixes IZPACK-1588 by using standard Java API

### PR DESCRIPTION
**Pull request by reinhapa**

### CODE REVIEW

**Comment by reinhapa** [comment]
@rkrell with this small change it is posible to install/uninstall using JDK 9 when built with a JDK8 and prior. This would help enough in our use case for now

**Comment by reinhapa** [comment]
@rkrell can you please look into this PR as it would be important for us to start going forward to JDK 9

**Comment by rkrell** [comment]
Thank you and sorry for the big delay.

**Comment by triceo** [comment]
@rkrell Is there a plan to release 5.1.3 any time soon? Considering that 5.1.2 won't work on Java 9.

**Comment by rkrell** [comment]
> @rkrell Is there a plan to release 5.1.3 any time soon? Considering that 5.1.2 won't work on Java 9.
I would do soon, but at the moment there is a problem again with openjdk6 and oraclejdk7 support on Travis, for example:
```
$ jdk_switcher use openjdk6
Switching to OpenJDK6 (java-1.6.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-6-openjdk-amd64
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-1.6.0-openjdk-amd64
```
I'd like to find a way around it. It seems the apt packages are installed after the above phase. Any idea how we could save JDK6 support in Travis?

**Comment by triceo** [comment]
@rkrell As far as I know, Travis dropped support for JDK 6. Which is not surprising - Oracle stopped supporting Java 6 a long time ago.

Not sure if you're aware of this:
https://docs.travis-ci.com/user/languages/java/#Updating-Oracle-JDK-to-a-recent-release

It doesn't specifically mention Java 6, but I found out that the installer exists for 6 as well:
https://www.ubuntuupdates.org/package/webupd8_java/trusty/main/base/oracle-java6-installer

So perhaps that's something to try.

**Comment by akuhtz** [comment]
@rkrell 
Might be related to this:
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

Adding this
`dist: precise`

Looked at https://github.com/sbt/sbt/blob/0.13/.travis.yml and this worked, [13 days ago](https://travis-ci.org/sbt/sbt/builds/297791644) at least.

**Comment by rkrell** [comment]
> @rkrell
> Might be related to this:
> https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
> 
> Adding this
> dist: precise
> 
> Looked at https://github.com/sbt/sbt/blob/0.13/.travis.yml and this worked, 13 days ago at least.

@akuhtz Thanks. In fact this is related, unfortunately with this line added most of the builds just hardly crash. I left this commit for inside to the build results.

**Comment by triceo** [comment]
@rkrell Seems that the builds are green now - can we get a release compatible with Java 9 now, pretty pretty please?

**Comment by reinhapa** [comment]
@triceo I started already with that and got the build running [here](https://github.com/reinhapa/izpack/tree/jdk9-build). The problem remaining is that some of the libraries itself are not ready for JDK 9 and later releases jet... :-(

**Comment by triceo** [comment]
@reinhapa That is unfortunate. I see two possibilities:

- Either release what we have now, since the most obvious problem (for me) will disappear and IZPack will be more useful than before. Incremental progress.

- Or release a version of IZPack that doesn't allow to launch the installer on Java 9. Because the behavior of 5.1.2 is that the installer gets all the way to the final step, and then fails when actually installing. Which is super annoying and there isn't any obvious way to make the installer ignore Java 9. In my opinion, if we know Java 9 is not supported, IZPack shouldn't mislead users to thinking that it is.

**Comment by reinhapa** [comment]
@triceo the current master branch is executable with Java 9 so @rkrell only has to make an new release for that.

**Comment by akuhtz** [comment]
@reinhapa Regarding Java 9:  Have you used the language selection dialog under Java 9. Last time I tried it the flags in the combo were correct but the languange name was 'English' for every item.

**Comment by reinhapa** [comment]
@akuhtz there is a problem with the language selection in Java 9, can you try with a build of my fork?

**Comment by akuhtz** [comment]
@reinhapa I cloned your master but I cannot build using Java 9. Java 8 seems to be broken if running on Win7 with admin privileges in the util module, even on the izpack master.
Did you pass some special params to J9 build? Because I got `ClassNotFoundException: javax.xml.bind.JAXBException`.

**Comment by reinhapa** [comment]
@akuhtz  try to set the following environment variable for maven:
`MAVEN_OPTS=--add-modules java.xml.bind `

**Comment by akuhtz** [comment]
@reinhapa I found the issue in the registry on my machine that prevent me from building. Now I started to build your jdk9-build and it fails in the `DefaultLocalesTest.testLangPacks` where it processes the following (the first line is a sysout I added, the 2nd line is line 106):
`From code.toLowerCase(): 'eng' to locales.getISOCode().toLowerCase(): 'deu'`
`assertEquals(code.toLowerCase(), locales.getISOCode().toLowerCase());`

My language is english but my locale is german .... Might be another issue.

**Pull request merged**
