### PR TITLE
IZPACK-1613: Fixed issue with wrong locale under Java 9.

### PR DESCRIPTION
**Pull request by akuhtz**
This PR fixes the problem with the wrong language in the language selection dialog under Java 9+. The flag was correct, but the language was always 'English'.

### CODE REVIEW

**Comment by rkrell** [comment]
It seems the JDK 6 build on Travis is broken. This probably hasn't been caused by your change, but some change in the infrastructure.

After searching for the cause of 
> Received fatal alert: protocol_version 
it seems there has to be introduced a JVM option `-Dhttps.protocols=TLSv1.2` for that particular JDK. Can you give it a try.

**Comment by rkrell** [comment]
I commit a change in .travis.yml directly to the master branch - you may try to merge it to your PR and retry the build, or modify it according to your needs.

**Comment by akuhtz** [comment]
The issue with JDK 6 persists :-(

**Comment by rkrell** [comment]
> The issue with JDK 6 persists :-(
> Not sure if the problem is that the JAVA_OPTS is defined already. Are you sure to not use MAVEN_OPTS?

I saw it. `JAVA_OPTS` is defined but it can be overridden in the matrix. I'm not dealing with Travis every day, but I'll try my best to help with this.

**Comment by akuhtz** [comment]
@rkrell It passes now. Thank you for fixing this.

**Comment by akuhtz** [comment]
@rkrell Not sure if I get you right (Sunday morning ...  :simple_smile: ) but the null check is inside the `isEmpty()`:
```
private boolean isEmpty(String var) 
{
   return (var == null || var.isEmpty());
}
```

**Comment by rkrell** [comment]
Thanks for finally solving this hopefully last showstopper for newer JDKs.

**Pull request merged**
