### PR TITLE
Izpack 1485 make continuation on failure configurable

### PR DESCRIPTION
**Pull request by jwillebrands**
This is fix for proposed improvement https://izpack.atlassian.net/browse/IZPACK-1485

### CODE REVIEW

**Comment by rkrell** [comment]
Excuses, I think I misunderstood you a bit and looked again into your change. I haven't recognized for the first time you ask every time if allowContinueOnFail="true", otherwise, when overriding it, the messagebox is just not shown. So this is ok of course. I should better not do reviews on fridays :-)

Maybe the attribute could be renamed to express its intention better, like `askOnFailure` or so. What do you think?

**Comment by jwillebrands** [comment]
Apologies, priorities shifted somewhat causing this to slip from attention.

I agree with renaming the attribute, onError with options ask/fail is more clear. 

I am unsure about the three-state flag. I cannot imagine a process failing that would always be fine to ignore. In my opinion a failed process is always reason for failure of the installation, or at the very least up to the user's discretion. I'll leave that decision up to you.

As for the automated installation mode failing on error, this would actually be a change from the current behaviour. Currently if a process fails, the installer simply continues. I am in favor of halting on errors, however this would change behaviour from previous version. Again, I'll leave that decision up to you.

**Comment by rkrell** [comment]
Thanks. I'll accept this, I believe this is a nice improvement for the ProcessPanel.

Would you mind to add this to the according documentation with the "Since: IzPack 5.1" hint? Because this is the upcoming release coming very soon (we're in RC3 at the moment).

**Comment by jwillebrands** [comment]
Thank you. I've updated the ProcessPanel wiki page accordingly.

**Pull request merged**
