### PR TITLE
[IZPACK-1738] always show overwrite files dialog on new installation

### PR DESCRIPTION
**Pull request by fcorneli**
…allation directory

### CODE REVIEW

**Review by reinhapa — CHANGES_REQUESTED** [review]

**Comment by reinhapa** [comment]
@fcorneli also check for the failing tests  and change them to reflect your enhancement too...

**Comment by fcorneli** [comment]
@reinhapa See my latest commit. `Boolean.parseBoolean` instead of `Boolean.getBoolean`. Now the big question: how could this ever work?

**Comment by reinhapa** [comment]
> @reinhapa See my latest commit. `Boolean.parseBoolean` instead of `Boolean.getBoolean`. Now the big question: how could this ever work?

Autoboxing....


@fcorneli can you rebase your PR to the current `master` branch?

**Comment by fcorneli** [comment]
@reinhapa Done.

**Review by reinhapa — APPROVED** [review]

**Review by akuhtz — APPROVED** [review]

**Pull request merged**
