### PR TITLE
IZPACK-1406 + IZPACK-1260: Improvements of dynamic variables handling

### PR DESCRIPTION
**Pull request by Helpstone**
This is an implementation of [IZPACK-1406](https://izpack.atlassian.net/browse/IZPACK-1406) and [IZPACK-1260](https://izpack.atlassian.net/browse/IZPACK-1260). It is the reincarnation of pull request #509 :
> Closing this, my latest changes have been merged to https://github.com/Helpstone/izpack/tree/IZPACK-1406_with_conditions and we'll expecting a brand-new pull request from there.

**Details:**
At the moment, there are dynamic variables saved as lists of a DynamicVariable list for one variable name, without considering references among them (unresolved values ${...} as part of a variable defintion) referring to another dynamic variable. To make the resolving as most complete as possible, dynamic variables are resolved in a limited number of cycles.

To optimize this, there could be done the following changes:

-  Analyze the direct value references between variables and pre-order them at compile time using a directed graph, so that the variables dependent on "others" are shifted after the "others". The result is a pre-ordered list of dynamic variables compiled-in to the installer. Cycles should not be a problem, there should been left unresolved variables in this case (example: a={b}\, b={a} -> a=={b}, b=={b} ).
- Simplify the DefaultVariables implementation by relying on pre-ordering of the dynamic variables as provided by the list compiled in. This means especially resolving them in one cycle instead of repeating resolving several times. This could also improve the performance of variable resolution especially for installers having a big set of variables accessing files.
- During compiling, there could be overgiven a List<DynamicVariable> instead of Map<String, List<DynamicVariable>> to the installer as serialized object.

### CODE REVIEW

**Comment by rkrell** [comment]
What an impressive piece of work!
I'm afraid nobody will immediately honour it without looking under the hood. No matter :+1: 
I'll check this with some of my installers.

**Comment by Helpstone** [comment]
yes, but is our common work! And you are the initiator.
:-)
 
-----Ursprüngliche Nachricht-----
 Von: "René Krell" [notifications@github.com]
 Gesendet: Mi. 22.06.2016 11:57
 An: "izpack/izpack" [izpack@noreply.github.com]
 Kopie: "Helpstone" [dth@freenet.de],  "Author" [author@noreply.github.com]
 Betreff: Re: [izpack/izpack] IZPACK-1406 + IZPACK-1260: Improvements of dynamic variables handling (#527)

What an impressive piece of work!
 I'm afraid nobody will immediately honour it without looking under the hood. No matter �� 
 I'll check this with some of my installers.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-----Ursprüngliche Nachricht Ende-----


---
Mail & Cloud Made in Germany mit 3 GB Speicher! Jetzt kostenlos anmelden

**Comment by rkrell** [comment]
At the end you wrote the bigger part of it and in a perfect manner. Many thanks!

For me, this implementation looks good, which means it compiles and passes the unit tests on Linux and runs perfectly in a more complex installer.

We can fine-tune some details later in a separate pull request.
If you are ok with the state I'm ready to merge it.

And probably also going to release the overdue version 5.0.9.

**I'm still waiting for your final OK** to do so.

**Comment by Helpstone** [comment]
The (simple|complex) expression language for conditions in variables is not handled yet in PackagerBase.buildVariableList()

**Comment by Helpstone** [comment]
The pull request should be feature complete now. The expression language does work now.

Please test your installers!

**Comment by rkrell** [comment]
> The pull request should be feature complete now. The expression language does work now.
> 
> Please test your installers!

Many thanks. Going to merge and check the latest state.

**Comment by rkrell** [comment]
BTW: If you agree and if there are no really critical issues, i'd made this request the cut for 5.0.9, we can continue in 5.0.10.

**Comment by Helpstone** [comment]
IZPACK-1406 as last PR for 5.0.9 or as first in 5.0.10 ? Both would be ok ...

**Comment by rkrell** [comment]
> IZPACK-1406 as last PR for 5.0.9 or as first in 5.0.10 ? Both would be ok ...

IZPACK-1406 as last PR for 5.0.9.
If there isn't anything obvious we introduced along with the 5.0.9 changes, of course...

**Comment by rkrell** [comment]
Ok, fine with my installers and worth to be integrated now.
Thanks again

**Comment by domdop** [comment]
Ich werde ab  24.06.2016 nicht im B�ro sein. Ich kehre zur�ck am
05.07.2016.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [izpack/izpack] IZPACK-1406 + IZPACK-1260: Improvements of dynamic
variables handling (#527)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2016 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Pull request merged**
