### PR TITLE
fix for running tests on Windows without administrative rights

### PR DESCRIPTION
**Pull request by Murdock01**

### CODE REVIEW

**Comment by rkrell** [comment]
Thank you.

**Comment by akuhtz** [comment]
This just skips the tests without any notice if administrative rights were required ... Is this intended?

**Comment by rkrell** [comment]
It skips just there, where the build would fail otherwise. Since the registry access is optional we need some chance to pass the tests for less privileged user accounts.
I don't have a better idea at the moment.

**Comment by akuhtz** [comment]
@rkrell Maybe change to use Assume.assumeTrue() that skips the test and not pass the test. 
See http://stackoverflow.com/questions/1689242/conditionally-ignoring-tests-in-junit-4

**Comment by rkrell** [comment]
@akuhtz Good idea, looks clean. Would you be able to modify this in this way in another PR?

**Comment by akuhtz** [comment]
@rkrell While adding Assume I got test failures running as Administrator. I'll test tonight at home.

**Comment by Murdock01** [comment]
Hi,
it was originally my intention to fix this in this way, additionally we
can write some log messages, that tests are skipped because they need
administrative rights.

But for my understanding, the normal developer should not work on his
system with administrative rights and UAC switched off (as it is also in
almost all other OS since long time), so i believe the standard
operation modus is user with restricted rights.

If there are changes on the code, that writes to the registry, the user
can switch to god mode and than these tests also runs.

But if the proposed way with Assume works, it will be also fine, the
only important point for me is, that tests must not be switched off at
all, if a user works on his system in the way, that is normal in the
current times.

just my two cents.

Peter (aka Murdock01)

Am 16.02.2016 um 14:29 schrieb Andreas Kuhtz:

**Comment by akuhtz** [comment]
Running as Administrator:
`Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 0`

Running not as admin:
`Results :

Tests run: 14, Failures: 0, Errors: 0, Skipped: 4`

**Comment by Murdock01** [comment]
Hi,

nice, than we can do this in this way.
@akuhtz can you provide the changes?
@rkrell maybe this is a cleaner solution.


Am 16.02.2016 um 20:42 schrieb Andreas Kuhtz:

**Comment by akuhtz** [comment]
Hi,

I provided PR 448 that skips the tests. See my comments there.

**Pull request merged**
