### PR TITLE
Use temporary directory to avoid deleting existing directories.

### PR DESCRIPTION
**Pull request by sebster**
New pull request which works on JDK 1.6.

### CODE REVIEW

**Comment by rkrell** [comment]
I do understand the problem with this implementation and I'm glad you point this out.
But I'm still in doubt with this implementation.
I'd rather trim down the IzPack FileUtils class and one day to remove it, to be honest.

From my point of view you don't need this new utility method
`com.izforge.izpack.util.file.FileUtils.createTempDirectory("izpack", TEMP_DIR)`
and it isn't necessary to do mkdirs() multiple times at different directory levels. FileUtils.forceMkdir(dir) does complement all missing directories in the file system.

Can't it be done easier this way:
```java
        // This corrects issues that could arise due to subfolders
        Collections.sort(allDirList);
        File tmpRoot = File.createTempFile("izpack", "", TEMP_DIR);        
        for (String dirName : allDirList)
        {
            File tmp = new File(tmpRoot, dirName);
            org.apache.commons.io.FileUtils.forceMkdir(tmp);
            org.apache.commons.io.FileUtils.forceDeleteOnExit(tmp);
            String target = targetdir + "/" + dirName;
            logAddingFile(tmp.toString(), target);
            pack.addFile(baseDir, tmp, target, osList,
                         override, overrideRenameTo, blockable, additionals, condition);
        }
        org.apache.commons.io.FileUtils.forceDeleteOnExit(tmpRoot);
```

Maybe I miss some detail, I'd just like to understand it better.

**Comment by sebster** [comment]
You're creating a temp file in the above code:

File tmp = new File(tmpRoot, dirName)

This creates a file and not a directory, so trying to create the file in the following line:

File tmp = new File(tmpRoot, dirName);

will fail because the tmpRoot is an existing file and not a directory. Initially you would think to delete the tmpRoot file which File.createTempFile makes because otherwise you cannot recreate it as a directory. Unfortunately, if you call tmpRoot.delete() it's not necessarily immediate, so most probably the directory create will fail anyway because the tmpRoot file is still in the way. That's why I chose to create a directory with a DIFFERENT name from the tmp file which was created. See also the discussion on: http://stackoverflow.com/questions/617414/create-a-temporary-directory-in-java

Note that the code adds a bunch of empty directories as a different target every time, I'm wondering why it's not just possible to call pack.addFile with the same empty directory and a different target each time instead of creating a whole file tree of empty directories on disk.

**Comment by rkrell** [comment]
I see, you're right. `File.createTempFile("izpack", "", TEMP_DIR)` would create an empty file, not a directory. The only workaround would be using a hash, like at the link you referred to, thus `new File(TEMP_DIR, Long.toString(System.nanoTime())`.
So we will keep this solution unless JDK 7 will be the minimum requirement (which I would introduce not before a next major version - there are people still using it in older projects).

**Comment by rkrell** [comment]
> I'm wondering why it's not just possible to call pack.addFile with the same empty directory and a different target each time instead of creating a whole file tree of empty directories on disk.

You're invited to improve this :-)

**Comment by rkrell** [comment]
Thank you for finding out and fixing this.

**Pull request merged**
