### PR TITLE
Izpack 1182: Evaluation of dynamic variables, which depends on other ones

### PR DESCRIPTION
**Pull request by Helpstone**
With this fix the dynamic variables, which depend on other ones, are computated correct on the first refresh() already. The Issue is olved with this pull request.

### CODE REVIEW

**Comment by rkrell** [comment]
Unfortunately this breaks the latest implementation of blocking variables reserved by panels.
I will check this, soon.

**Comment by Helpstone** [comment]
The last update does resolve a loop for a variable with several conditions.
Does this also resolve your problem wirh blocking variables (which probably also have several conditions)?
I'll do some more testing and probably implement a check for loops

**Comment by rkrell** [comment]
I'll check this soon, but it should not break older environments, relying on the order of definition of the dynamic variables. Thanks for your action.

**Comment by rkrell** [comment]
It works so far, well-done.
Thank you.

**Pull request merged**
