### PR TITLE
IZPACK-1654: Fix broken travis build

### PR DESCRIPTION
**Pull request by akuhtz**
IZPACK-1654: Fix broken travis build

### CODE REVIEW

**Comment by reinhapa** [comment]
@akuhtz Unfortunately the build fails again do to even more tight security requirements (HTTPS)

**Comment by akuhtz** [comment]
@reinhapa Yes, time moves :-) I'm not tied to JDK6. Thank you for moving on.

**Comment by reinhapa** [comment]
@akuhtz @rkrell I would suggest to raise the minimum JDK bar to at least 8...

**Comment by rkrell** [comment]
OK from my point of view.

In this case
- I'd increase the new release version to 5.2.0 (master branch)
- created a Git branch 5.1 to reflect the breaking change and to allow
anyone who sits on JRE 6 to maintain the old version.

čt 12. 3. 2020 v 10:42 odesílatel Patrick Reinhart <notifications@github.com>
napsal:

**Pull request merged**
