### PR TITLE
[IZPACK-1702] Optional parameter to be used while searching loose files

### PR DESCRIPTION
**Pull request by fdulger**
If provided, search for loose files in folder specified by 'looseFilesDir' property.

### CODE REVIEW

**Comment by fdulger** [comment]
A workaround for the problem described here https://izpack.atlassian.net/browse/IZPACK-1702

**Comment by reinhapa** [comment]
@akuhtz seems reasonable for me

**Review by akuhtz — APPROVED** [review]
Looks good to me.

**Comment by fdulger** [comment]
Hi again, @reinhapa 
Is there any update on this? I still see the old 5.2.0-SNAPSHOT (the one from 08/04/21) on Sonatype repo. Sorry to bother you with this but we would like to use this in our project. I would be glad to help in any way if I can.

**Comment by reinhapa** [comment]
@fdulger I'm still in the progress of getting access in order to publish snapshots/releases...

**Comment by akuhtz** [comment]
@reinhapa Shall I publish a snapshot?

**Comment by rkrell** [comment]
Reinhard has got  access to deploy artifacts to the sonatype repositry now,
which should be replicated to Maven Central, as far as I remember:

[image: jorlina]Joel Orlina
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=jorlina> added a
comment - 8 hours ago

Permissions granted to reinhapa for publishing under this groupId on
https://oss.sonatype.org


So Reinhard could try.


If there should be another one for deployments let me know.


Thank you,

René



st 22. 9. 2021 v 10:58 odesílatel Andreas Kuhtz ***@***.***>
napsal:

**Comment by reinhapa** [comment]
@rkrell @fdulger I successfully added the automatic publish of SNAPSHOT builds for the `master` branch.

**Comment by fdulger** [comment]
@reinhapa thanks a lot!

**Pull request merged**
