### PR TITLE
added missing polish translation

### PR DESCRIPTION
**Pull request by Suuwi**

### CODE REVIEW

**Comment by rkrell** [comment]
Can you please fix the build?

**Comment by akuhtz** [comment]
> 
> 
> Can you please fix the build?

@rkrell https://github.com/izpack/izpack/pull/698

**Comment by reinhapa** [comment]
@Suuwi can you please update your PR by updating to the latest `master` and possibly open also an issue https://izpack.atlassian.net/ for this?

**Comment by hiteshbosamiya** [comment]
@reinhapa, I have raised an issue and created new PR https://github.com/izpack/izpack/pull/769. Please close this PR.

**Pull request closed without merging**
