### PR TITLE
[IZPACK-1749] InstallationType has no console panel or automation helper

### PR DESCRIPTION
**Pull request by hiteshbosamiya**
The implementation takes JP (the reporter)'s code and modified it further.

### CODE REVIEW

**Review by akuhtz — COMMENTED** [review]
@hiteshbosamiya Are the changes covered by a test?

**Comment by hiteshbosamiya** [comment]
> @hiteshbosamiya Are the changes covered by a test?

No, they are not. Will write the tests and let you know.

**Review by jpadre — APPROVED** [review]

**Review by jpadre — APPROVED** [review]

**Review by jpadre — APPROVED** [review]
Reviewed and approved

**Comment by hiteshbosamiya** [comment]
@akuhtz, added the tests, please review. Thanks.

**Review by akuhtz — APPROVED** [review]
Excellent! Thank you @hiteshbosamiya  👍 💯

**Pull request merged**
