### PR TITLE
IZPACK-1295

### PR DESCRIPTION
**Pull request by stenix71**
Pull request that fixes IZPACK-1295
https://izpack.atlassian.net/browse/IZPACK-1295

Fixed problem that packs were installed in wrong order while using console mode.

This is a show-stopper for us so I would appreciate swift handling.
Cheers
Jonas

### CODE REVIEW

**Comment by stenix71** [comment]
Should I close a pull request or leave it open? Sorry, I am a bit new to Github.

**Comment by stenix71** [comment]
Ok, I found it. I should leave it open. It was not my intention to add both these files to the same pull-request. My intention was to create two pull requests. Hope this does not complicate things at your end.

**Comment by rkrell** [comment]
This comes in time. Release 5.0.6  will be marked by console installer fixes and improvements.
BTW, the updated swedish language pack should be also merged?

**Comment by rkrell** [comment]
Thanks for contributing.

**Comment by stenix71** [comment]
It is fine by me to merge the Swedish language pack as well. I just added translations to some strings that had been added to the English language pack but did not exist in the Swedish pack.

**Comment by rkrell** [comment]
It is very appreciated to help with translations, if you are a native speaker. Great!

**Comment by rkrell** [comment]
Please test the latest 5.0.6-SNAPSHOT from Sonatype OSS Snapshots or compiled from master, whether it fits for you. Planned to be released soon.

**Comment by stenix71** [comment]
I have tested the console installer compiled from master and as far as I can see it works fine now. I have found some minor issues about <executable> that was not related to this release so I will file a new bug report about that.

**Pull request merged**
