### PR TITLE
Fixed NPE if logconfig is not available.

### PR DESCRIPTION
**Pull request by akuhtz**
https://izpack.atlassian.net/browse/IZPACK-1513

### CODE REVIEW

**Comment by rkrell** [comment]
Very good catch, thanks.

Just one small intervention from my side - personally I'd used the default levels of the Java ConsoleHandler (INFO) and FileHandler (ALL), also to avoid meaningless reports.

**Comment by rkrell** [comment]
Because if one gets more or less information in the log he/she will probably automatically suspect the level, but getting nothing looks like an error. ☺️

**Comment by rkrell** [comment]
After a second review I'm not sure about the default, because at this phase it has been OFF already before.

So your solution is probably clean. I'll check it later on a normal computer, hard to see on a mobile phone 🙂

**Comment by akuhtz** [comment]
Hi René,
Ok. Feel free to change it :-)
If you deploy a new snapshot I'll test it :-)

René Krell <notifications@github.com> schrieb am Sa., 11. März 2017 um
18:10 Uhr:

**Pull request merged**
